#pragma once

#include <stdint.h>


/* -LICENSE-START-
 ** Copyright (c) 2016 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */


// Register 'IDENTIFIER'
static const uint16_t	kRegIDENTIFIER       = 0x0000;
static const uint16_t	kRegIDENTIFIER_Width = 4;
static const uint16_t	kRegIDENTIFIER_Start = 0x0000;
static const uint16_t	kRegIDENTIFIER_End   = 0x0003;

// Register Field 'IDENTIFIER.IDENTITY'
static const uint16_t	kRegIDENTIFIER_IDENTITY_Offset = 0;
static const uint16_t	kRegIDENTIFIER_IDENTITY_Width  = 32;
static const uint32_t	kRegIDENTIFIER_IDENTITY_Mask   = 0xffffffff;

// Register 'FWVERSION'
static const uint16_t	kRegFWVERSION       = 0x0004;
static const uint16_t	kRegFWVERSION_Width = 2;
static const uint16_t	kRegFWVERSION_Start = 0x0004;
static const uint16_t	kRegFWVERSION_End   = 0x0005;

// Register Field 'FWVERSION.MINOR'
static const uint16_t	kRegFWVERSION_MINOR_Offset = 0;
static const uint16_t	kRegFWVERSION_MINOR_Width  = 8;
static const uint16_t	kRegFWVERSION_MINOR_Mask   = 0x00ff;

// Register Field 'FWVERSION.MAJOR'
static const uint16_t	kRegFWVERSION_MAJOR_Offset = 8;
static const uint16_t	kRegFWVERSION_MAJOR_Width  = 8;
static const uint16_t	kRegFWVERSION_MAJOR_Mask   = 0xff00;

// Register 'PVERSION'
static const uint16_t	kRegPVERSION       = 0x0006;
static const uint16_t	kRegPVERSION_Width = 2;
static const uint16_t	kRegPVERSION_Start = 0x0006;
static const uint16_t	kRegPVERSION_End   = 0x0007;

// Register Field 'PVERSION.MINOR'
static const uint16_t	kRegPVERSION_MINOR_Offset = 0;
static const uint16_t	kRegPVERSION_MINOR_Width  = 8;
static const uint16_t	kRegPVERSION_MINOR_Mask   = 0x00ff;

// Register Field 'PVERSION.MAJOR'
static const uint16_t	kRegPVERSION_MAJOR_Offset = 8;
static const uint16_t	kRegPVERSION_MAJOR_Width  = 8;
static const uint16_t	kRegPVERSION_MAJOR_Mask   = 0xff00;

// Register 'CONTROL'
static const uint16_t	kRegCONTROL       = 0x1000;
static const uint16_t	kRegCONTROL_Width = 1;
static const uint16_t	kRegCONTROL_Start = 0x1000;
static const uint16_t	kRegCONTROL_End   = 0x1000;

// Register Field 'CONTROL.COVERIDE'
static const uint16_t	kRegCONTROL_COVERIDE_Offset = 0;
static const uint16_t	kRegCONTROL_COVERIDE_Width  = 1;
static const uint8_t	kRegCONTROL_COVERIDE_Mask   = 0x01;

// Register Field 'CONTROL.TOVERIDE'
static const uint16_t	kRegCONTROL_TOVERIDE_Offset = 1;
static const uint16_t	kRegCONTROL_TOVERIDE_Width  = 1;
static const uint8_t	kRegCONTROL_TOVERIDE_Mask   = 0x02;

// Register Field 'CONTROL.TRESET'
static const uint16_t	kRegCONTROL_TRESET_Offset = 2;
static const uint16_t	kRegCONTROL_TRESET_Width  = 1;
static const uint8_t	kRegCONTROL_TRESET_Mask   = 0x04;

// Register Field 'CONTROL.OOVERIDE'
static const uint16_t	kRegCONTROL_OOVERIDE_Offset = 3;
static const uint16_t	kRegCONTROL_OOVERIDE_Width  = 1;
static const uint8_t	kRegCONTROL_OOVERIDE_Mask   = 0x08;

// Register 'OCARM'
static const uint16_t	kRegOCARM       = 0x2000;
static const uint16_t	kRegOCARM_Width = 1;
static const uint16_t	kRegOCARM_Start = 0x2000;
static const uint16_t	kRegOCARM_End   = 0x2000;

// Register Field 'OCARM.ARM'
static const uint16_t	kRegOCARM_ARM_Offset = 0;
static const uint16_t	kRegOCARM_ARM_Width  = 1;
static const uint8_t	kRegOCARM_ARM_Mask   = 0x01;

// Register 'OCLENGTH'
static const uint16_t	kRegOCLENGTH       = 0x2001;
static const uint16_t	kRegOCLENGTH_Width = 1;
static const uint16_t	kRegOCLENGTH_Start = 0x2001;
static const uint16_t	kRegOCLENGTH_End   = 0x2001;

// Register Field 'OCLENGTH.LENGTH'
static const uint16_t	kRegOCLENGTH_LENGTH_Offset = 0;
static const uint16_t	kRegOCLENGTH_LENGTH_Width  = 8;
static const uint8_t	kRegOCLENGTH_LENGTH_Mask   = 0xff;

// Register 'OCDATA'
static const uint16_t	kRegOCDATA       = 0x2100;
static const uint16_t	kRegOCDATA_Width = 255;
static const uint16_t	kRegOCDATA_Start = 0x2100;
static const uint16_t	kRegOCDATA_End   = 0x21fe;

// Register 'ICARM'
static const uint16_t	kRegICARM       = 0x3000;
static const uint16_t	kRegICARM_Width = 1;
static const uint16_t	kRegICARM_Start = 0x3000;
static const uint16_t	kRegICARM_End   = 0x3000;

// Register Field 'ICARM.ARM'
static const uint16_t	kRegICARM_ARM_Offset = 0;
static const uint16_t	kRegICARM_ARM_Width  = 1;
static const uint8_t	kRegICARM_ARM_Mask   = 0x01;

// Register 'ICLENGTH'
static const uint16_t	kRegICLENGTH       = 0x3001;
static const uint16_t	kRegICLENGTH_Width = 1;
static const uint16_t	kRegICLENGTH_Start = 0x3001;
static const uint16_t	kRegICLENGTH_End   = 0x3001;

// Register Field 'ICLENGTH.LENGTH'
static const uint16_t	kRegICLENGTH_LENGTH_Offset = 0;
static const uint16_t	kRegICLENGTH_LENGTH_Width  = 8;
static const uint8_t	kRegICLENGTH_LENGTH_Mask   = 0xff;

// Register 'ICDATA'
static const uint16_t	kRegICDATA       = 0x3100;
static const uint16_t	kRegICDATA_Width = 255;
static const uint16_t	kRegICDATA_Start = 0x3100;
static const uint16_t	kRegICDATA_End   = 0x31fe;

// Register 'OTARM'
static const uint16_t	kRegOTARM       = 0x4000;
static const uint16_t	kRegOTARM_Width = 1;
static const uint16_t	kRegOTARM_Start = 0x4000;
static const uint16_t	kRegOTARM_End   = 0x4000;

// Register Field 'OTARM.ARM'
static const uint16_t	kRegOTARM_ARM_Offset = 0;
static const uint16_t	kRegOTARM_ARM_Width  = 1;
static const uint8_t	kRegOTARM_ARM_Mask   = 0x01;

// Register 'OTLENGTH'
static const uint16_t	kRegOTLENGTH       = 0x4001;
static const uint16_t	kRegOTLENGTH_Width = 1;
static const uint16_t	kRegOTLENGTH_Start = 0x4001;
static const uint16_t	kRegOTLENGTH_End   = 0x4001;

// Register Field 'OTLENGTH.LENGTH'
static const uint16_t	kRegOTLENGTH_LENGTH_Offset = 0;
static const uint16_t	kRegOTLENGTH_LENGTH_Width  = 8;
static const uint8_t	kRegOTLENGTH_LENGTH_Mask   = 0xff;

// Register 'OTDATA'
static const uint16_t	kRegOTDATA       = 0x4100;
static const uint16_t	kRegOTDATA_Width = 255;
static const uint16_t	kRegOTDATA_Start = 0x4100;
static const uint16_t	kRegOTDATA_End   = 0x41fe;

// Register Field 'OTDATA.PROGRAM'
static const uint16_t	kRegOTDATA_PROGRAM_Offset = 0;
static const uint16_t	kRegOTDATA_PROGRAM_Width  = 1;
static const uint8_t	kRegOTDATA_PROGRAM_Mask   = 0x01;

// Register Field 'OTDATA.PREVIEW'
static const uint16_t	kRegOTDATA_PREVIEW_Offset = 1;
static const uint16_t	kRegOTDATA_PREVIEW_Width  = 1;
static const uint8_t	kRegOTDATA_PREVIEW_Mask   = 0x02;

// Register 'ITARM'
static const uint16_t	kRegITARM       = 0x5000;
static const uint16_t	kRegITARM_Width = 1;
static const uint16_t	kRegITARM_Start = 0x5000;
static const uint16_t	kRegITARM_End   = 0x5000;

// Register Field 'ITARM.ARM'
static const uint16_t	kRegITARM_ARM_Offset = 0;
static const uint16_t	kRegITARM_ARM_Width  = 1;
static const uint8_t	kRegITARM_ARM_Mask   = 0x01;

// Register 'ITLENGTH'
static const uint16_t	kRegITLENGTH       = 0x5001;
static const uint16_t	kRegITLENGTH_Width = 1;
static const uint16_t	kRegITLENGTH_Start = 0x5001;
static const uint16_t	kRegITLENGTH_End   = 0x5001;

// Register Field 'ITLENGTH.LENGTH'
static const uint16_t	kRegITLENGTH_LENGTH_Offset = 0;
static const uint16_t	kRegITLENGTH_LENGTH_Width  = 8;
static const uint8_t	kRegITLENGTH_LENGTH_Mask   = 0xff;

// Register 'ITDATA'
static const uint16_t	kRegITDATA       = 0x5100;
static const uint16_t	kRegITDATA_Width = 255;
static const uint16_t	kRegITDATA_Start = 0x5100;
static const uint16_t	kRegITDATA_End   = 0x51fe;

// Register Field 'ITDATA.PROGRAM'
static const uint16_t	kRegITDATA_PROGRAM_Offset = 0;
static const uint16_t	kRegITDATA_PROGRAM_Width  = 1;
static const uint8_t	kRegITDATA_PROGRAM_Mask   = 0x01;

// Register Field 'ITDATA.PREVIEW'
static const uint16_t	kRegITDATA_PREVIEW_Offset = 1;
static const uint16_t	kRegITDATA_PREVIEW_Width  = 1;
static const uint8_t	kRegITDATA_PREVIEW_Mask   = 0x02;

